const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
let playwright;try{playwright=require('playwright');}catch{playwright=require('node:module').createRequire(path.resolve(__dirname,'../browser/package.json'))('playwright');}
const root=path.resolve(__dirname,'../..'),out=process.env.PETS_LIVES_ARTIFACT_DIR||'/tmp/pets-lives-evidence';fs.mkdirSync(out,{recursive:true});
(async()=>{
 let now=1791540000;const {fixture}=await import(root+'/testing/pets/fixture.mjs'),f=fixture({clock:()=>now});
 const {createPetRouter}=await import(root+'/worker/pets.js'),{persistPetCommand}=await import(root+'/worker/pet-store.js'),{PET_LIFE_RULES:rules}=await import(root+'/worker/pet-life-rules.js');
 const router=createPetRouter({validateSession:async req=>req.headers.get('authorization')==='Bearer pet-demo-a'?f.user:null});
 const checks=[],errors=[],note=name=>{checks.push(name);console.log('PASS',name);},stored=()=>JSON.parse(f.sql.prepare('SELECT state_json FROM pet_accounts WHERE auth_username=?').get(f.user.username).state_json),put=s=>f.sql.prepare('UPDATE pet_accounts SET state_json=? WHERE auth_username=?').run(JSON.stringify(s),f.user.username);
 const server=http.createServer(async(req,res)=>{try{
  const url=new URL(req.url,'http://127.0.0.1');res.setHeader('Cache-Control','no-store');
  if(url.pathname.startsWith('/api/pets/')){let body='';for await(const c of req)body+=c;const r=await router(new Request(url,{method:req.method,headers:req.headers,...(['GET','HEAD'].includes(req.method)?{}:{body})}),{PETS_ENABLED:'true',AUTH_DB:f.db});res.writeHead(r.status,Object.fromEntries(r.headers));return res.end(await r.text());}
  if(url.pathname==='/js/auth-config.js'){res.setHeader('Content-Type','text/javascript');return res.end('window.REGULATION_AUTH_CONFIG={endpoint:location.origin,enforcement:true};');}
  if(url.pathname.startsWith('/api/')){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(url.pathname==='/api/auth/me'?{user:{username:'demo-a',name:'Synthetic',role:'cidadao',active:true,emailVerified:true,sessionVersion:1}}:{backendEnabled:false,available:false,homeEnabled:false}));}
  let relative=url.pathname.slice(1);if(!relative||relative.endsWith('/'))relative+='index.html';const file=path.resolve(root,relative);if(!file.startsWith(root+'/')){res.writeHead(400);return res.end();}
  res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));
 }catch{res.writeHead(500);res.end('Synthetic fixture error');}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
 const browser=await playwright.chromium.launch({...(process.env.PETS_BROWSER_EXECUTABLE?{executablePath:process.env.PETS_BROWSER_EXECUTABLE}:{}),headless:true,args:['--no-sandbox']}),context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await context.newPage();
 await context.addInitScript(()=>{sessionStorage.setItem('regulacao.portal.session','pet-demo-a');sessionStorage.setItem('regulacao.portal.user',JSON.stringify({username:'demo-a',name:'Synthetic',role:'cidadao',active:true,emailVerified:true,sessionVersion:1}));sessionStorage.setItem('regulacao.portal.user.validatedAt',String(Date.now()));});
 await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.goto(origin+'/mascotes/');await page.waitForFunction(()=>window.PortalPets);await page.getByRole('button',{name:'Gato dourado',exact:true}).click();assert.equal(storedOptional(),null);await page.locator('#petAdopt').click();await page.waitForFunction(()=>window.PortalPets.runtime.state.pet?.variant==='ginger');
  assert.equal(await page.locator('.pet-heart').count(),7);assert.equal(await page.locator('.pet-heart[data-filled=true]').count(),7);assert.equal(await page.locator('#petLives').getAttribute('aria-label'),'7 de 7 vidas');assert(await page.locator('#petAdopt').isDisabled());assert(await page.getByRole('button',{name:'Gato cinza',exact:true}).isDisabled());note('selection waits for adoption; seven pixel hearts and one living cat');
  f.sql.prepare('UPDATE pet_accounts SET balance=40').run();await page.evaluate(()=>window.PortalPets.runtime.refresh());const bowl=page.locator('.pet-item').filter({has:page.getByRole('heading',{name:'Potinho de água',exact:true})});assert.match(await bowl.innerText(),/20 moedas/);await bowl.getByRole('button',{name:'Comprar',exact:true}).click();await page.waitForFunction(()=>window.PortalPets.runtime.state.inventory['water-bowl']===1);assert.equal(await page.evaluate(()=>window.PortalPets.runtime.state.balance),20);assert.equal(stored().life.bowlProtectionSeconds,rules.bowlProtectionSeconds);note('virtual-coin pot purchase equips and fills for 48 active care hours');
  let s=stored();s.life.lives=6;s.life.bowlProtectionSeconds=1;put(s);await page.evaluate(()=>window.PortalPets.runtime.refresh());assert.equal(await page.locator('.pet-heart[data-filled=true]').count(),6);await bowl.getByRole('button',{name:'Encher potinho · grátis',exact:true}).click();await page.waitForFunction(()=>window.PortalPets.runtime.state.life.bowlProtectionSeconds===172800);assert.equal(stored().life.lives,6);assert.equal(await page.evaluate(()=>window.PortalPets.runtime.state.balance),20);note('free refill preserves lost lives and coins');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'seven-lives-mobile.png'),fullPage:true});note('mobile hearts, fullness and pot fit without horizontal overflow');
  const staleView=await page.evaluate(()=>window.PortalPets.runtime.state);
  s=stored();s.preferences.needsPaused=false;s.preferences.schedule={timezone:'Etc/UTC',days:[0,1,2,3,4,5,6],start:0,end:1440};s.life.waterBowl=null;s.life.foodSeconds=rules.foodSeconds;s.life.waterSeconds=rules.waterSeconds;s.life.hungerCriticalSeconds=rules.hungerLifeSeconds-1;s.life.thirstCriticalSeconds=rules.thirstLifeSeconds-1;s.life.lives=2;put(s);
  const tab=crypto.randomUUID(),base={tabId:tab,visible:true,focused:true,recentlyInteracted:true};let r=await persistPetCommand(f.db,f.user,'activity',{...base,operationId:crypto.randomUUID(),sequence:1});now++;await persistPetCommand(f.db,f.user,'activity',{...base,operationId:crypto.randomUUID(),sequence:2,leaseToken:r.receipt.leaseToken});await page.evaluate(()=>window.PortalPets.runtime.refresh());
  assert.equal(await page.locator('.pet-stage').isVisible(),false);assert.equal(await page.locator('.pet-heart[data-filled=true]').count(),0);assert.match(await page.locator('#petLifeStatus').innerText(),/perdeu as sete vidas/);for(const button of await page.locator('[data-care]').all())assert(await button.isDisabled());assert.equal(await page.getByRole('button',{name:'Gato cinza',exact:true}).isDisabled(),false);note('permanent death hides companion, disables care and unlocks gallery');
  await page.evaluate(s=>window.PortalPets.runtime.update(s),staleView);assert.equal(await page.evaluate(()=>window.PortalPets.runtime.state.life.lives),0);assert.equal(await page.locator('.pet-stage').isVisible(),false);note('late older response cannot visually resurrect the dead cat');
  await page.goto(origin+'/ferramentas/');await page.waitForFunction(()=>window.PortalPets?.runtime.state.life.lives===0);assert.equal(await page.locator('.pet-stage-global').isVisible(),false);await page.goto(origin+'/mascotes/');await page.waitForFunction(()=>window.PortalPets?.runtime.state.life.lives===0);await page.getByRole('button',{name:'Gato cinza',exact:true}).click();await page.locator('#petAdopt').click();await page.waitForFunction(()=>window.PortalPets.runtime.state.pet.variant==='gray'&&window.PortalPets.runtime.state.life.lives===7);assert.equal(stored().deathHistory.length,1);assert.equal(stored().inventory['water-bowl'],1);assert.equal(stored().life.bowlProtectionSeconds,0);note('death stays hidden across modules; new adoption retains history and inventory');
  await page.reload();await page.waitForFunction(()=>window.PortalPets?.runtime.state.pet.variant==='gray'&&window.PortalCitizenShell?.active().url.pathname==='/mascotes/'&&!window.PortalCitizenShell.diagnostics().navigating);await page.locator('#petLives').waitFor();assert.equal(await page.locator('.pet-heart[data-filled=true]').count(),7);note('new cat and seven lives survive reload');
  const legacy=stored();delete legacy.life;delete legacy.deathHistory;legacy.hunger=85;legacy.thirst=90;put(legacy);const before=JSON.stringify(stored());await page.evaluate(()=>window.PortalPets.runtime.refresh());assert.equal(await page.locator('.pet-heart[data-filled=true]').count(),7);assert.equal(JSON.stringify(stored()),before);assert.equal(await page.evaluate(()=>window.PortalPets.runtime.state.life.lives),7);note('legacy cat renders seven lives without writes or retroactive damage');
  assert.deepEqual(errors,[]);note('no uncaught UI errors');fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors},null,2));
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,failure:e.stack},null,2));throw e;}
 finally{await context.close();await browser.close();server.close();f.close();}
 function storedOptional(){return f.sql.prepare('SELECT state_json FROM pet_accounts WHERE auth_username=?').get(f.user.username)||null;}
})().catch(e=>{console.error(e);process.exitCode=1;});
