const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
let playwright;try{playwright=require('playwright');}catch{playwright=require('node:module').createRequire(path.resolve(__dirname,'../browser/package.json'))('playwright');}const {chromium}=playwright;
const root=path.resolve(__dirname,'../..'),baseline=process.env.PETS_GLOBAL_BASELINE;
const out=process.env.PETS_SPEECH_ARTIFACT_DIR||'/tmp/pets-speech-evidence';fs.mkdirSync(out,{recursive:true});
const checks=[],petErrors=[],mutations=[];
(async()=>{
 const {fixture}=await import(root+'/testing/pets/fixture.mjs');const f=fixture();
 const {createPetRouter}=await import(root+'/worker/pets.js');
 const router=createPetRouter({validateSession:async r=>{const t=r.headers.get('Authorization');return ['Bearer pet-demo-a','Bearer pet-demo-b'].includes(t)?{username:t.endsWith('-b')?'demo-b':'demo-a',sessionVersion:1,mustChangePassword:false}:null;}});
 const {persistPetCommand}=await import(root+'/worker/pet-store.js');
 await persistPetCommand(f.db,f.user,'adopt',{operationId:crypto.randomUUID(),typeId:'cat',variant:'gray',expectedPetRevision:0});
 await persistPetCommand(f.db,{username:'demo-b',sessionVersion:1},'adopt',{operationId:crypto.randomUUID(),typeId:'cat',variant:'ginger',expectedPetRevision:0});
 const original=JSON.parse(f.sql.prepare("SELECT state_json FROM pet_accounts WHERE auth_username='demo-a'").get().state_json);
 const server=http.createServer(async(req,res)=>{
  try{
   const url=new URL(req.url,'http://127.0.0.1');res.setHeader('Cache-Control','no-store');
   if(url.pathname==='/home-race.html'){res.setHeader('Content-Type','text/html');return res.end('<!doctype html><html><head><script src="/js/auth-config.js"></script><script src="/js/auth-client.js"></script><script>window.PortalHomeReady=new Promise(resolve=>window.finishPetHome=resolve);</script><script type="module" src="/js/pets-bootstrap.js"></script></head><body><header class="portal-topbar">Synthetic Home</header><main id="homeLoading">Loading</main></body></html>');}
   if(url.pathname.startsWith('/api/pets/')){
    if(req.method==='POST')mutations.push(url.pathname);let body='';for await(const chunk of req)body+=chunk;
    const response=await router(new Request(url,{method:req.method,headers:req.headers,...(['GET','HEAD'].includes(req.method)?{}:{body})}),{PETS_ENABLED:'true',AUTH_DB:f.db});
    res.writeHead(response.status,Object.fromEntries(response.headers));return res.end(await response.text());
   }
   if(url.pathname==='/js/auth-config.js'){res.setHeader('Content-Type','text/javascript');return res.end('window.REGULATION_AUTH_CONFIG={endpoint:location.origin,enforcement:true};');}
   if(url.pathname.startsWith('/api/')){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(url.pathname==='/api/social/config'?{backendEnabled:false,available:false,homeEnabled:false}:url.pathname==='/api/auth/me'?{user:{username:req.headers.authorization?.endsWith('-b')?'demo-b':'demo-a',name:'Synthetic',role:'admin',active:true,emailVerified:true,sessionVersion:1}}:{}));}
   let relative=url.pathname.slice(1);if(!relative||relative.endsWith('/'))relative+='index.html';
   const filename=path.resolve(root,relative);if(!filename.startsWith(root+'/')){res.writeHead(400);return res.end();}
   let data;
   try{data=baseline?execFileSync('git',['show',baseline+':'+relative],{cwd:root,stdio:['ignore','pipe','ignore']}):fs.readFileSync(filename);}catch{res.writeHead(404);return res.end();}
   res.setHeader('Content-Type',({'.js':'text/javascript','.mjs':'text/javascript','.html':'text/html','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.json':'application/json'})[path.extname(filename)]||'application/octet-stream');res.end(data);
  }catch{res.writeHead(500);res.end('Synthetic fixture error');}
 });
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({...(process.env.PETS_BROWSER_EXECUTABLE?{executablePath:process.env.PETS_BROWSER_EXECUTABLE}:{}),headless:true,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:1280,height:900},serviceWorkers:'block'}),page=await context.newPage();
 await context.addInitScript(()=>{if(!sessionStorage.getItem('regulacao.portal.session'))sessionStorage.setItem('regulacao.portal.session','pet-demo-a');sessionStorage.setItem('regulacao.portal.user',JSON.stringify({username:sessionStorage.getItem('regulacao.portal.session').endsWith('-b')?'demo-b':'demo-a',name:'Synthetic',role:'admin',active:true,emailVerified:true,sessionVersion:1}));sessionStorage.setItem('regulacao.portal.user.validatedAt',String(Date.now()));});
 await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 page.on('pageerror',e=>{if(/pets-|pet-cat|pet-phrases/.test(e.stack||''))petErrors.push(e.message);});
 const note=(name,detail)=>{checks.push({name,detail});console.log('PASS',name,JSON.stringify(detail));};
 async function state(){await page.waitForFunction(()=>window.PortalPets?.runtime.state.pet?.variant==='gray');assert.equal(await page.locator('.pet-stage').count(),1);return page.evaluate(()=>window.PortalPets.runtime.state);}
 async function geometry(){return page.locator('.pet-stage').evaluate(e=>{const r=e.getBoundingClientRect();return {position:getComputedStyle(e).position,events:getComputedStyle(e).pointerEvents,top:r.top,bottom:r.bottom,left:r.left,right:r.right,width:innerWidth,height:innerHeight,global:e.classList.contains('pet-stage-global')};});}
 await context.addInitScript(()=>{window.__speechClock=Number(sessionStorage.getItem('speech-test-clock'))||Date.now();Date.now=()=>window.__speechClock;});
 const clock=async time=>page.evaluate(time=>{window.__speechClock=time;sessionStorage.setItem('speech-test-clock',String(time));},time);
 const snapshot=()=>page.evaluate(()=>({cycle:window.PortalPets.runtime.speech.cycle.snapshot(),nextAt:window.PortalPets.runtime.speech.nextAt,until:window.PortalPets.runtime.speech.bubbleUntil,key:window.PortalPets.runtime.speech.key,time:Date.now()}));
 const emit=async()=>{const before=await snapshot();await clock(before.nextAt);await page.waitForFunction(last=>window.PortalPets.runtime.speech.cycle.lastId!==last,before.cycle.lastId);return snapshot();};
 try{
  await page.goto(origin+'/ferramentas/');await state();let s=await snapshot();assert(s.nextAt-s.time>=25000&&s.nextAt-s.time<=40000);await clock(s.nextAt-100);await page.waitForTimeout(150);assert.equal(await page.locator('.pet-bubble').isVisible(),false);note('first neutral phrase waits within approved 25–40 seconds',{});
  s=await emit();const text=await page.locator('.pet-bubble').innerText();assert(text);assert.equal(s.until-s.time,7000);assert(s.nextAt-s.time>=25000&&s.nextAt-s.time<=40000);await clock(s.until-1);await page.waitForTimeout(150);assert.equal(await page.locator('.pet-bubble').isVisible(),true);await clock(s.until);await page.waitForFunction(()=>window.PortalPets.runtime.bubble.hidden);note('neutral bubble lasts seven seconds and next deadline stays approved',{text});
  const first=s;await page.goto(origin+'/estudos/');await state();s=await snapshot();assert.deepEqual(s.cycle,first.cycle);assert.equal(s.nextAt,first.nextAt);await page.reload();await state();s=await snapshot();assert.deepEqual(s.cycle,first.cycle);assert.equal(s.nextAt,first.nextAt);note('module change and reload preserve remaining IDs and deadline',{});
  const seen=new Set([s.cycle.lastId]);for(let i=0;i<66;i++){s=await emit();assert(!seen.has(s.cycle.lastId));seen.add(s.cycle.lastId);}assert.equal(seen.size,67);assert.equal(s.cycle.remaining.length,0);const last=s.cycle.lastId;s=await emit();assert.notEqual(s.cycle.lastId,last);assert.equal(s.cycle.remaining.length,66);note('all 67 phrases appear once per cycle; boundary never repeats immediately',{});
  await page.screenshot({path:path.join(out,'speech-cycle.png')});
  const beforeAlert=await snapshot();await page.evaluate(()=>{const r=window.PortalPets.runtime;r.update({...r.state,thirst:80});});await clock(beforeAlert.nextAt);await page.waitForTimeout(200);assert.match(await page.locator('.pet-bubble').innerText(),/sede/);assert.deepEqual((await snapshot()).cycle,beforeAlert.cycle);await page.evaluate(()=>{const r=window.PortalPets.runtime;r.update({...r.state,thirst:0});});await page.waitForFunction(last=>window.PortalPets.runtime.speech.cycle.lastId!==last,beforeAlert.cycle.lastId);note('needs alert has priority and does not consume unseen neutral phrases',{});
  let paused=await snapshot();await page.evaluate(()=>{const r=window.PortalPets.runtime;r.update({...r.state,preferences:{...r.state.preferences,visible:false}});});await clock(paused.nextAt);await page.waitForTimeout(150);assert.deepEqual((await snapshot()).cycle,paused.cycle);assert.equal(await page.locator('.pet-stage').isVisible(),false);await page.evaluate(()=>{const r=window.PortalPets.runtime;r.update({...r.state,preferences:{...r.state.preferences,visible:true}});});await page.waitForFunction(last=>window.PortalPets.runtime.speech.cycle.lastId!==last,paused.cycle.lastId);note('explicit hide stops selection and preserves the cycle',{});
  paused=await snapshot();await page.emulateMedia({reducedMotion:'reduce'});await clock(paused.nextAt);await page.waitForTimeout(150);assert.deepEqual((await snapshot()).cycle,paused.cycle);await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForFunction(last=>window.PortalPets.runtime.speech.cycle.lastId!==last,paused.cycle.lastId);note('existing reduced-motion behavior is preserved',{});
  paused=await snapshot();await page.evaluate(()=>{const d=document.createElement('dialog');d.id='speech-modal';d.textContent='Synthetic modal';document.body.append(d);d.showModal();});await clock(paused.nextAt);await page.waitForTimeout(150);assert.equal(await page.locator('.pet-stage').isVisible(),false);assert.deepEqual((await snapshot()).cycle,paused.cycle);await page.evaluate(()=>document.getElementById('speech-modal').remove());await page.waitForFunction(last=>window.PortalPets.runtime.speech.cycle.lastId!==last,paused.cycle.lastId);note('hidden modal decoration never consumes an unseen phrase',{});
  const a=await snapshot();await page.evaluate(()=>{window.RegulationAuth.clearSession();sessionStorage.setItem('regulacao.portal.session','pet-demo-b');window.dispatchEvent(new CustomEvent('portal:session-ready'));});await page.waitForFunction(()=>window.PortalPets?.runtime.state.pet?.variant==='ginger');let b=await snapshot();assert.notEqual(b.key,a.key);assert.equal(b.cycle.lastId,null);assert.deepEqual(b.cycle.remaining,[]);await emit();await page.evaluate(()=>{window.RegulationAuth.clearSession();sessionStorage.setItem('regulacao.portal.session','pet-demo-a');window.dispatchEvent(new CustomEvent('portal:session-ready'));});await page.waitForFunction(()=>window.PortalPets?.runtime.state.pet?.variant==='gray');assert.deepEqual((await snapshot()).cycle,a.cycle);note('account B gets a separate cycle and returning to A restores A',{});
  await page.evaluate(()=>{const key=window.PortalPets.runtime.speech.key,s=JSON.parse(sessionStorage.getItem(key));s.version='old-catalog';s.remaining=['old-id'];sessionStorage.setItem(key,JSON.stringify(s));});await page.reload();await state();s=await snapshot();assert.equal(s.cycle.lastId,null);assert.deepEqual(s.cycle.remaining,[]);assert(s.nextAt-s.time>=25000&&s.nextAt-s.time<=40000);await emit();note('catalog version mismatch safely resets IDs and first deadline',{});
  const records=await page.evaluate(()=>Object.keys(sessionStorage).filter(k=>k.startsWith('portal:pets:speech:')).map(k=>({key:k,value:JSON.parse(sessionStorage.getItem(k))})));for(const record of records){assert(!record.key.includes('pet-demo'));assert.deepEqual(Object.keys(record.value).sort(),['bubbleUntil','lastId','nextAt','remaining','version']);assert(record.value.remaining.every(id=>/^phrase-\d{3}$/.test(id)));}assert.deepEqual(mutations,[]);assert.deepEqual(petErrors,[]);note('only catalog IDs and deadlines stored; no pet API writes or page errors',{accounts:records.length});
 }catch(e){await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,petErrors,mutations,failure:e.stack},null,2));throw e;}
 finally{await context.close();await browser.close();server.close();f.close();}
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,petErrors,mutations},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
